Repository corda/corda-docs-portal, pull requests merged in 2021-11, with the labels that each got.

#319 DOC-3367: Corda OS 4.1 link fixes
  content/en/platform/corda/4.1/open-source/api-contract-constraints.md
  content/en/platform/corda/4.1/open-source/api-flows.md
  content/en/platform/corda/4.1/open-source/api-scanner.md
  content/en/platform/corda/4.1/open-source/api-vault-query.md
  content/en/platform/corda/4.1/open-source/app-upgrade-notes.md
  content/en/platform/corda/4.1/open-source/aws-vm.md
  content/en/platform/corda/4.1/open-source/azure-vm.md
  content/en/platform/corda/4.1/open-source/changelog.md
  content/en/platform/corda/4.1/open-source/cli-ux-guidelines.md
  content/en/platform/corda/4.1/open-source/clientrpc.md
  content/en/platform/corda/4.1/open-source/contributing-philosophy.md
  content/en/platform/corda/4.1/open-source/contributing.md
  content/en/platform/corda/4.1/open-source/corda-api.md
  content/en/platform/corda/4.1/open-source/corda-configuration-file.md
  content/en/platform/corda/4.1/open-source/corda-network/UAT.md
  content/en/platform/corda/4.1/open-source/corda-network/the-corda-network.md
  content/en/platform/corda/4.1/open-source/cordapp-build-systems.md
  content/en/platform/corda/4.1/open-source/cordapp-constraint-migration.md
  content/en/platform/corda/4.1/open-source/cordapp-overview.md
  content/en/platform/corda/4.1/open-source/cordapp-upgradeability.md
  content/en/platform/corda/4.1/open-source/debugging-a-cordapp.md
  content/en/platform/corda/4.1/open-source/demobench.md
  content/en/platform/corda/4.1/open-source/deploying-a-node.md
  content/en/platform/corda/4.1/open-source/deterministic-modules.md
  content/en/platform/corda/4.1/open-source/flow-state-machines.md
  content/en/platform/corda/4.1/open-source/generating-a-node.md
  content/en/platform/corda/4.1/open-source/hello-world-template.md
  content/en/platform/corda/4.1/open-source/json.md
  content/en/platform/corda/4.1/open-source/network-bootstrapper.md
  content/en/platform/corda/4.1/open-source/network-builder.md
  content/en/platform/corda/4.1/open-source/node-administration.md
  content/en/platform/corda/4.1/open-source/node-upgrade-notes.md
  content/en/platform/corda/4.1/open-source/oracles.md
  content/en/platform/corda/4.1/open-source/quickstart-build.md
  content/en/platform/corda/4.1/open-source/release-notes.md
  content/en/platform/corda/4.1/open-source/running-a-node.md
  content/en/platform/corda/4.1/open-source/testing.md
  content/en/platform/corda/4.1/open-source/tutorial-cordapp.md
  content/en/platform/corda/4.1/open-source/tutorial-tear-offs.md
  content/en/platform/corda/4.1/open-source/versioning.md
  content/en/platform/corda/4.4/open-source/demobench.md
Labels: bug, documentation, team technical writing, dev preview, internal

#327 DOC-3444: Added the Set up and test the UI C5 tutorial
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-running.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-ui.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/mission-mars-ui.PNG
Labels: documentation, team technical writing, waiting for SME review, tutorials

#334 DOC-3328 Corrected colour by changing html code from attention (unsupported) to note.
  content/en/platform/corda/5.0-dev-preview-1/packaging/cordapp-builder.md
Labels: bug, documentation, team technical writing, dev preview

#333 DOC-3474: [Customer-facing] Add UI demo and instructions to Solar System CorDapp tutorial
  content/en/platform/corda/5.0-dev-preview-1/tutorials/run-demo-cordapp.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/solar-system-earth.png
  content/en/platform/corda/5.0-dev-preview-1/tutorials/solar-system-home.png
Labels: documentation, enhancement, team technical writing, waiting for SME review, tutorials

#335 DOC-3357-2: CE 4.3 link fixes (part 2)
  content/en/platform/corda/4.3/enterprise/api-stability-guarantees.md
  content/en/platform/corda/4.3/enterprise/changelog-enterprise.md
  content/en/platform/corda/4.3/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.3/enterprise/clientrpc.md
  content/en/platform/corda/4.3/enterprise/corda-configuration-file.md
  content/en/platform/corda/4.3/enterprise/corda-network/the-corda-network.md
  content/en/platform/corda/4.3/enterprise/cordapp-advanced-concepts.md
  content/en/platform/corda/4.3/enterprise/cordapp-build-systems.md
  content/en/platform/corda/4.3/enterprise/cordapp-constraint-migration.md
  content/en/platform/corda/4.3/enterprise/cordapp-overview.md
  content/en/platform/corda/4.3/enterprise/cordapp-upgradeability.md
  content/en/platform/corda/4.3/enterprise/database-management.md
  content/en/platform/corda/4.3/enterprise/debugging-a-cordapp.md
  content/en/platform/corda/4.3/enterprise/deploying-a-node.md
  content/en/platform/corda/4.3/enterprise/flow-state-machines.md
  content/en/platform/corda/4.3/enterprise/generating-a-node.md
  content/en/platform/corda/4.3/enterprise/getting-set-up.md
  content/en/platform/corda/4.3/enterprise/hello-world-template.md
  content/en/platform/corda/4.3/enterprise/metering-collector.md
  content/en/platform/corda/4.3/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.3/enterprise/network-map.md
  content/en/platform/corda/4.3/enterprise/node-administration.md
  content/en/platform/corda/4.3/enterprise/node-database-admin.md
  content/en/platform/corda/4.3/enterprise/node-database-developer.md
  content/en/platform/corda/4.3/enterprise/node-database.md
  content/en/platform/corda/4.3/enterprise/node-naming.md
  content/en/platform/corda/4.3/enterprise/node-operations-cordapp-deployment.md
  content/en/platform/corda/4.3/enterprise/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.3/enterprise/node-operations-upgrading-os-to-ent.md
  content/en/platform/corda/4.3/enterprise/running-a-node.md
  content/en/platform/corda/4.3/enterprise/running-a-notary.md
  content/en/platform/corda/4.3/enterprise/shell.md
  content/en/platform/corda/4.3/enterprise/tutorial-cordapp.md
  content/en/platform/corda/4.3/enterprise/tutorial-tear-offs.md
  content/en/platform/corda/4.3/enterprise/versioning-and-upgrades.md
Labels: bug, documentation, team technical writing

#330 DOC-3357: CE 4.3 link fixes (part 1)
  content/en/platform/corda/4.3/enterprise/api-contract-constraints.md
  content/en/platform/corda/4.3/enterprise/api-flows.md
  content/en/platform/corda/4.3/enterprise/api-testing.md
  content/en/platform/corda/4.3/enterprise/api-vault-query.md
  content/en/platform/corda/4.3/enterprise/app-upgrade-notes-enterprise.md
  content/en/platform/corda/4.3/enterprise/corda-firewall-component.md
  content/en/platform/corda/4.3/enterprise/corda-firewall-configuration-fields.md
  content/en/platform/corda/4.3/enterprise/corda-firewall-configuration-file.md
  content/en/platform/corda/4.3/enterprise/corda-firewall-upgrade.md
  content/en/platform/corda/4.3/enterprise/corda-firewall.md
  content/en/platform/corda/4.3/enterprise/cryptoservice-configuration.md
  content/en/platform/corda/4.3/enterprise/node-database-intro.md
  content/en/platform/corda/4.3/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.3/enterprise/notary-reg-tool.md
  content/en/platform/corda/4.3/enterprise/performance-testing/installation.md
  content/en/platform/corda/4.3/enterprise/performance-testing/introduction.md
  content/en/platform/corda/4.3/enterprise/performance-testing/performance-tuning.md
  content/en/platform/corda/4.3/enterprise/performance-testing/running-jmeter-corda.md
  content/en/platform/corda/4.3/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/faq/notary-failover.md
  content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/faq/toctree.md
  content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/handling-flag-days.md
  content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/installing-jpa.md
  content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/notary-db-migration.md
  content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/upgrading-the-ha-notary-service.md
  content/en/platform/corda/4.3/enterprise/version-compatibility.md
Labels: bug, documentation, team technical writing

#336 DOC-3585: Update CRDB version on platform support matrix / notary deployment
  content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
Labels: documentation, external

#331 DOC-3512: Notary FAQ bugs and rewrite
  content/en/platform/corda/4.8/enterprise/notary/faq/eta-mechanism.md
  content/en/platform/corda/4.8/enterprise/notary/faq/notary-failover.md
  content/en/platform/corda/4.8/enterprise/notary/faq/notary-latency-monitoring.md
  content/en/platform/corda/4.8/enterprise/notary/faq/notary-load-balancing.md
Labels: bug, documentation

#283 DOC-3356 Link Fixes CE 4.4 (Part 1)
  content/en/platform/corda/4.4/enterprise/app-upgrade-notes-enterprise.md
  content/en/platform/corda/4.4/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.4/enterprise/changelog.md
  content/en/platform/corda/4.4/enterprise/cordapps/cordapp-build-systems.md
  content/en/platform/corda/4.4/enterprise/cordapps/cordapp-compatibility.md
  content/en/platform/corda/4.4/enterprise/cordapps/cordapp-constraint-migration.md
  content/en/platform/corda/4.4/enterprise/cordapps/cordapp-overview.md
  content/en/platform/corda/4.4/enterprise/cordapps/cordapp-upgradeability.md
  content/en/platform/corda/4.4/enterprise/cordapps/database-management.md
  content/en/platform/corda/4.4/enterprise/cordapps/debugging-a-cordapp.md
  content/en/platform/corda/4.4/enterprise/cordapps/deterministic-jvm.md
  content/en/platform/corda/4.4/enterprise/cordapps/flow-cookbook.md
  content/en/platform/corda/4.4/enterprise/cordapps/getting-set-up.md
  content/en/platform/corda/4.4/enterprise/cordapps/upgrading-cordapps.md
  content/en/platform/corda/4.4/enterprise/cordapps/writing-a-cordapp.md
  content/en/platform/corda/4.4/enterprise/network/azure-vm.md
  content/en/platform/corda/4.4/enterprise/network/corda-networks.md
  content/en/platform/corda/4.4/enterprise/network/setting-up-a-dynamic-compatibility-zone.md
  content/en/platform/corda/4.4/enterprise/node/component-topology.md
  content/en/platform/corda/4.4/enterprise/node/corda-firewall-component.md
  content/en/platform/corda/4.4/enterprise/node/corda-firewall-configuration-fields.md
  content/en/platform/corda/4.4/enterprise/node/deploy/deploying-a-node.md
  content/en/platform/corda/4.4/enterprise/node/deploy/env-dev.md
  content/en/platform/corda/4.4/enterprise/node/deploy/env-prod-test.md
  content/en/platform/corda/4.4/enterprise/node/deploy/generating-a-node.md
  content/en/platform/corda/4.4/enterprise/node/deploy/running-a-node.md
  content/en/platform/corda/4.4/enterprise/node/deploy/starting-components.md
  content/en/platform/corda/4.4/enterprise/node/operating/clientrpc.md
  content/en/platform/corda/4.4/enterprise/node/operating/cm-backup.md
  content/en/platform/corda/4.4/enterprise/node/operating/cm-updating-cordapp.md
  content/en/platform/corda/4.4/enterprise/node/operating/cm-upgrading-node.md
  content/en/platform/corda/4.4/enterprise/node/operating/cryptoservice-configuration.md
  content/en/platform/corda/4.4/enterprise/node/operating/monitoring-logging.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-administration.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-database-developer.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-database.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-operations-cordapp-deployment.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-operations-upgrading-os-to-ent.md
  content/en/platform/corda/4.4/enterprise/node/operating/optimizing.md
  content/en/platform/corda/4.4/enterprise/node/operating/shell.md
  content/en/platform/corda/4.4/enterprise/node/pki-guide.md
  content/en/platform/corda/4.4/enterprise/node/setup/corda-configuration-file.md
  content/en/platform/corda/4.4/enterprise/node/setup/host-prereq.md
  content/en/platform/corda/4.4/enterprise/node/setup/node-naming.md
Labels: bug, documentation, team technical writing, internal

#338 DOC-3592: Legal info and checksums for CE 4.8.2
  content/en/platform/corda/4.8/enterprise/legal-info-4.8.2.md
  content/en/platform/corda/4.8/enterprise/release-checksum-enterprise.md
Labels: documentation, release

#339 DOC-3577: Added info on encumbrances to key concepts.
  content/en/platform/corda/4.8/open-source/key-concepts-contracts.md
Labels: documentation

#345 DOC-3207 [Customer-facing] Add JsonMarshallingService service to Corda services
  content/en/platform/corda/5.0-dev-preview-1/cordapps/corda-services/json-marshalling.md
Labels: documentation, team technical writing, dev preview

#349 DOC-1779 [BNE] Missing repo link
  content/en/platform/corda/4.6/enterprise/network/business-network-membership.md
  content/en/platform/corda/4.6/open-source/business-network-membership.md
  content/en/platform/corda/4.7/enterprise/network/business-network-membership.md
  content/en/platform/corda/4.7/open-source/business-network-membership.md
  content/en/platform/corda/4.8/enterprise/network/business-network-membership.md
  content/en/platform/corda/4.8/open-source/business-network-membership.md
Labels: bug, documentation, team technical writing

#351 DOC-3430: Document automated installer ahead of manual
  content/en/platform/corda/5.0-dev-preview-1/packaging/cordapp-builder.md
Labels: bug, documentation, team technical writing, dev preview

#352 DOC-2192: Change "Corda Network Foundation" to "Corda Network"
  content/en/platform/corda/4.8/enterprise/corda-network/the-corda-network.md
  content/en/platform/corda/4.8/enterprise/cordapps/cordapp-constraint-migration.md
  content/en/platform/corda/4.8/open-source/corda-network/corda-network-foundation.md
Labels: bug, documentation, team technical writing, internal

#353 DOC-3609 - Fix typo on docs homepage.
  themes/doks/layouts/index.html
Labels: bug, documentation, team technical writing

#354 DOC-3434 Removed repeated links to code samples
  content/en/tutorials/corda/4.8/os/supplementary-tutorials/oracles.md
Labels: bug, documentation, team technical writing

#355 DOC-2898 Fixed incorrect definition of RPC in ENT 4.5 - 4.8.
  content/en/platform/corda/4.5/enterprise/node/setup/rpc-audit-data-recording.md
  content/en/platform/corda/4.6/enterprise/node/setup/rpc-audit-data-recording.md
  content/en/platform/corda/4.7/enterprise/node/setup/rpc-audit-data-recording.md
  content/en/platform/corda/4.8/enterprise/node/setup/rpc-audit-data-recording.md
Labels: bug, documentation, team technical writing

#356 DOC-1883 Fixed broken link for the Corda Network Builder in OS 4.3 - 4.8.
  content/en/platform/corda/4.3/open-source/network-builder.md
  content/en/platform/corda/4.4/open-source/network-builder.md
  content/en/platform/corda/4.5/open-source/network-builder.md
  content/en/platform/corda/4.6/open-source/network-builder.md
  content/en/platform/corda/4.7/open-source/network-builder.md
  content/en/platform/corda/4.8/open-source/network-builder.md
Labels: bug, documentation, team technical writing

#350 DOC-3598 Fix specified broken links in CE 4.8
  content/en/platform/corda/4.8/enterprise/node/gateway-service.md
Labels: bug, documentation, team technical writing

#359 DOC-3564: Text wrapping incorrectly in version number tables
  content/en/platform/corda/4.3/enterprise/platform-support-matrix.md
Labels: bug, documentation, good first issue

#358 DOC-3615: [Patch releases][Q4 2021][CE 4.8.3] Legal info page
  content/en/platform/corda/4.8/enterprise/legal-info-4.8.3.md
Labels: documentation, team technical writing, don't merge yet, release

#357 DOC-3616 Added checksums for ENT 4.8.3 release.
  content/en/platform/corda/4.8/enterprise/release-checksum-enterprise.md
Labels: documentation, team technical writing, release

#361 DOC-571: Removed the privateNetworkAutoEnrolment parameter from CENM 1.1 docs
  content/en/platform/corda/1.1/cenm/config-network-map-parameters.md
Labels: bug, documentation, team technical writing, waiting for SME review

#363 DOC-1879: Fix an error in host-prereqs page - "max" Java heap memory size should be "min"
  content/en/platform/corda/4.4/enterprise/node/setup/host-prereq.md
  content/en/platform/corda/4.5/enterprise/node/setup/host-prereq.md
  content/en/platform/corda/4.6/enterprise/node/setup/host-prereq.md
  content/en/platform/corda/4.7/enterprise/node/setup/host-prereq.md
  content/en/platform/corda/4.8/enterprise/node/setup/host-prereq.md
Labels: bug, documentation, team technical writing

#367 DOC-602 Update maxMessageSize description as per EG-2636 comments
  content/en/platform/corda/4.0/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.0/open-source/network-bootstrapper.md
  content/en/platform/corda/4.1/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.1/open-source/network-bootstrapper.md
  content/en/platform/corda/4.2/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.3/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.3/open-source/network-bootstrapper.md
  content/en/platform/corda/4.4/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.4/open-source/network-bootstrapper.md
  content/en/platform/corda/4.5/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.5/open-source/network-bootstrapper.md
  content/en/platform/corda/4.6/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.6/open-source/network-bootstrapper.md
  content/en/platform/corda/4.7/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.7/open-source/network-bootstrapper.md
Labels: bug, documentation, team technical writing

#368 DOC-545 Removed orphaned page and amended directs to reflect CE4.8
  content/en/platform/corda/4.1/enterprise/generating-a-node.md
  content/en/platform/corda/4.1/enterprise/node-database-developer.md
  content/en/platform/corda/4.2/enterprise/generating-a-node.md
  content/en/platform/corda/4.2/enterprise/node-database-developer.md
  content/en/platform/corda/4.2/enterprise/testing.md
  content/en/platform/corda/4.3/enterprise/generating-a-node.md
  content/en/platform/corda/4.3/enterprise/node-database-developer.md
  content/en/platform/corda/4.3/enterprise/testing.md
  content/en/platform/corda/4.4/enterprise/node/deploy/generating-a-node.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-database-developer.md
  content/en/platform/corda/4.4/enterprise/testing.md
  content/en/platform/corda/4.5/enterprise/node/operating/node-database-developer.md
  content/en/platform/corda/4.5/enterprise/testing.md
  content/en/platform/corda/4.8/enterprise/testing.md
Labels: bug, documentation, team technical writing

#369 DOC-3633 Release notes added for CE4.5.6
  content/en/platform/corda/4.5/enterprise/release-notes-enterprise.md
Labels: documentation, team technical writing, don't merge yet, release

#370 DOC-3634 Release notes added for CE4.6.5
  content/en/platform/corda/4.6/enterprise/release-notes-enterprise.md
Labels: documentation, team technical writing, don't merge yet, release

#371 DOC-3635 Release notes added for CE4.7.3
  content/en/platform/corda/4.7/enterprise/release-notes-enterprise.md
Labels: documentation, team technical writing, don't merge yet, release

#372 DOC-3631 Release notes added for CE4.3.8
  content/en/platform/corda/4.3/enterprise/release-notes-enterprise.md
Labels: documentation, team technical writing, don't merge yet, release

#373 DOC-3632 Release notes added for CE4.4.8
  content/en/platform/corda/4.4/enterprise/release-notes-enterprise.md
Labels: documentation, team technical writing, don't merge yet, release

#321 DOC-3356 Link Fixes CE 4.4 (Part 2)
  content/en/platform/corda/4.4/enterprise/app-upgrade-notes-enterprise.md
  content/en/platform/corda/4.4/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.4/enterprise/blob-inspector.md
  content/en/platform/corda/4.4/enterprise/changelog-enterprise.md
  content/en/platform/corda/4.4/enterprise/changelog.md
  content/en/platform/corda/4.4/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.4/enterprise/cordapp-advanced-concepts.md
  content/en/platform/corda/4.4/enterprise/database-management-tool.md
  content/en/platform/corda/4.4/enterprise/deterministic-modules.md
  content/en/platform/corda/4.4/enterprise/financial-model.md
  content/en/platform/corda/4.4/enterprise/ha-utilities.md
  content/en/platform/corda/4.4/enterprise/json.md
  content/en/platform/corda/4.4/enterprise/metering-collector.md
  content/en/platform/corda/4.4/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.4/enterprise/network/network-map.md
  content/en/platform/corda/4.4/enterprise/node-database-intro.md
  content/en/platform/corda/4.4/enterprise/node-explorer.md
  content/en/platform/corda/4.4/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.4/enterprise/node/deploy/deploying-a-node.md
  content/en/platform/corda/4.4/enterprise/notary/faq/notary-failover.md
  content/en/platform/corda/4.4/enterprise/notary/faq/toctree.md
  content/en/platform/corda/4.4/enterprise/notary/ha-notary-service-overview.md
  content/en/platform/corda/4.4/enterprise/notary/ha-notary-service-setup.md
  content/en/platform/corda/4.4/enterprise/notary/handling-flag-days.md
  content/en/platform/corda/4.4/enterprise/notary/hsm-support.md
  content/en/platform/corda/4.4/enterprise/notary/installing-jpa.md
  content/en/platform/corda/4.4/enterprise/notary/installing-the-notary-service-bootstrapper.md
  content/en/platform/corda/4.4/enterprise/notary/installing-the-notary-service.md
  content/en/platform/corda/4.4/enterprise/notary/machine-migration.md
  content/en/platform/corda/4.4/enterprise/notary/notary-db-migration.md
  content/en/platform/corda/4.4/enterprise/notary/notary-load-handling.md
  content/en/platform/corda/4.4/enterprise/notary/notary-metrics.md
  content/en/platform/corda/4.4/enterprise/notary/notary-sizing.md
  content/en/platform/corda/4.4/enterprise/notary/upgrading-the-ha-notary-service.md
  content/en/platform/corda/4.4/enterprise/performance-testing/installation.md
  content/en/platform/corda/4.4/enterprise/performance-testing/introduction.md
  content/en/platform/corda/4.4/enterprise/performance-testing/jmeter-samplers.md
  content/en/platform/corda/4.4/enterprise/performance-testing/jmeter-testplans.md
  content/en/platform/corda/4.4/enterprise/performance-testing/practical-considerations.md
  content/en/platform/corda/4.4/enterprise/performance-testing/r3-performance-runs.md
  content/en/platform/corda/4.4/enterprise/performance-testing/running-jmeter-corda.md
  content/en/platform/corda/4.4/enterprise/pki-tool.md
  content/en/platform/corda/4.4/enterprise/serialization-enum-evolution.md
  content/en/platform/corda/4.4/enterprise/upgrading-index.md
Labels: bug, documentation, team technical writing, internal

#376 DOC-3216: Make explicit on the getting started guide to review the platform support matrix
  content/en/platform/corda/4.5/open-source/getting-set-up.md
  content/en/platform/corda/4.6/open-source/getting-set-up.md
  content/en/platform/corda/4.7/open-source/getting-set-up.md
  content/en/platform/corda/4.8/open-source/getting-set-up.md
Labels: bug, documentation, propagating changes

#374 DOC-3640 DOC-3639 DOC-3638 DOC-3637 DOC-3636: Added legal info files for patch release.
  content/en/platform/corda/4.3/enterprise/legal-info-4.3.8.md
  content/en/platform/corda/4.4/enterprise/legal-info-4.4.8.md
  content/en/platform/corda/4.5/enterprise/legal-info-4.5.6.md
  content/en/platform/corda/4.6/enterprise/legal-info-4.6.5.md
  content/en/platform/corda/4.7/enterprise/legal-info-4.7.3.md
Labels: documentation, team technical writing, release

#377 DOC-3641 4.7.3 checksums
  content/en/platform/corda/4.7/enterprise/release-checksum-enterprise.md
Labels: team technical writing, release

#382 DOC-3646 4.3.8 checksums
  content/en/platform/corda/4.3/enterprise/release-checksum-enterprise.md
Labels: team technical writing, release

#378 DOC-3643 4.6.5 checksums
  content/en/platform/corda/4.3/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.4/enterprise/app-upgrade-notes-enterprise.md
  content/en/platform/corda/4.4/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.4/enterprise/blob-inspector.md
  content/en/platform/corda/4.4/enterprise/changelog-enterprise.md
  content/en/platform/corda/4.4/enterprise/changelog.md
  content/en/platform/corda/4.4/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.4/enterprise/cordapp-advanced-concepts.md
  content/en/platform/corda/4.4/enterprise/database-management-tool.md
  content/en/platform/corda/4.4/enterprise/deterministic-modules.md
  content/en/platform/corda/4.4/enterprise/financial-model.md
  content/en/platform/corda/4.4/enterprise/ha-utilities.md
  content/en/platform/corda/4.4/enterprise/json.md
  content/en/platform/corda/4.4/enterprise/metering-collector.md
  content/en/platform/corda/4.4/enterprise/network-bootstrapper.md
  content/en/platform/corda/4.4/enterprise/network/network-map.md
  content/en/platform/corda/4.4/enterprise/node-database-intro.md
  content/en/platform/corda/4.4/enterprise/node-explorer.md
  content/en/platform/corda/4.4/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.4/enterprise/node/deploy/deploying-a-node.md
  content/en/platform/corda/4.4/enterprise/notary/faq/notary-failover.md
  content/en/platform/corda/4.4/enterprise/notary/faq/toctree.md
  content/en/platform/corda/4.4/enterprise/notary/ha-notary-service-overview.md
  content/en/platform/corda/4.4/enterprise/notary/ha-notary-service-setup.md
  content/en/platform/corda/4.4/enterprise/notary/handling-flag-days.md
  content/en/platform/corda/4.4/enterprise/notary/hsm-support.md
  content/en/platform/corda/4.4/enterprise/notary/installing-jpa.md
  content/en/platform/corda/4.4/enterprise/notary/installing-the-notary-service-bootstrapper.md
  content/en/platform/corda/4.4/enterprise/notary/installing-the-notary-service.md
  content/en/platform/corda/4.4/enterprise/notary/machine-migration.md
  content/en/platform/corda/4.4/enterprise/notary/notary-db-migration.md
  content/en/platform/corda/4.4/enterprise/notary/notary-load-handling.md
  content/en/platform/corda/4.4/enterprise/notary/notary-metrics.md
  content/en/platform/corda/4.4/enterprise/notary/notary-sizing.md
  content/en/platform/corda/4.4/enterprise/notary/upgrading-the-ha-notary-service.md
  content/en/platform/corda/4.4/enterprise/performance-testing/installation.md
  content/en/platform/corda/4.4/enterprise/performance-testing/introduction.md
  content/en/platform/corda/4.4/enterprise/performance-testing/jmeter-samplers.md
  content/en/platform/corda/4.4/enterprise/performance-testing/jmeter-testplans.md
  content/en/platform/corda/4.4/enterprise/performance-testing/practical-considerations.md
  content/en/platform/corda/4.4/enterprise/performance-testing/r3-performance-runs.md
  content/en/platform/corda/4.4/enterprise/performance-testing/running-jmeter-corda.md
  content/en/platform/corda/4.4/enterprise/pki-tool.md
  content/en/platform/corda/4.4/enterprise/serialization-enum-evolution.md
  content/en/platform/corda/4.4/enterprise/upgrading-index.md
  content/en/platform/corda/4.5/open-source/getting-set-up.md
  content/en/platform/corda/4.6/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.6/open-source/getting-set-up.md
  content/en/platform/corda/4.7/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.7/open-source/getting-set-up.md
  content/en/platform/corda/4.8/open-source/getting-set-up.md
Labels: team technical writing, release

#365 DOC-526: Updated CENM 1.3, 1.4 and 1.5 deployment-kubernetes.md file
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
Labels: bug, documentation, team technical writing, waiting for SME review

#381 DOC-473: Added dependencies to reissuance docs.
  content/en/platform/corda/4.7/enterprise/cordapps/reissuing-states.md
  content/en/platform/corda/4.7/open-source/reissuing-states.md
  content/en/platform/corda/4.8/enterprise/cordapps/reissuing-states.md
  content/en/platform/corda/4.8/open-source/reissuing-states.md
Labels: bug, documentation, team technical writing, internal

#383 DOC-39: Version 4.1 in commands for 4.x release
  content/en/platform/corda/4.2/enterprise/operating/starting-components.md
  content/en/platform/corda/4.4/enterprise/node/deploy/starting-components.md
  content/en/platform/corda/4.5/enterprise/node/deploy/starting-components.md
  content/en/platform/corda/4.6/enterprise/node/deploy/starting-components.md
  content/en/platform/corda/4.7/enterprise/node/deploy/starting-components.md
  content/en/platform/corda/4.8/enterprise/node/deploy/starting-components.md
Labels: bug, documentation, propagating changes

#384 DOC-1850 [CENM 1.5] Missing attributes on Network Parameters page
  content/en/platform/corda/1.4/cenm/config-network-parameters.md
  content/en/platform/corda/1.5/cenm/config-network-parameters.md
Labels: bug

#386 DOC-1976 Removed step relating to upgrading to 4.6.
  content/en/platform/corda/4.5/enterprise/node/operating/cm-upgrading-node.md
Labels: bug, documentation

#387 DOC-1892: Removed error code that cannot be triggered.
  content/en/platform/corda/1.4/cenm/cenm-error-codes.md
  content/en/platform/corda/1.5/cenm/cenm-error-codes.md
Labels: bug, documentation

#380 DOC-3645 4.4.8 checksums
  content/en/platform/corda/4.4/enterprise/release-checksum-enterprise.md
Labels: release

#379 DOC-3644 4.5.6 checksums
  content/en/platform/corda/4.5/enterprise/release-checksum-enterprise.md
Labels: release

#391 DOC-3184: Broken link in CE 4.5 release notes
  content/en/platform/corda/4.5/enterprise/release-notes-enterprise.md
Labels: bug, documentation

#385 DOC-3408 [CENM 1.5] update the upgrade page to exclude CENM 1.2.1
  content/en/platform/corda/1.5/cenm/upgrade-notes.md
Labels: bug

#392 DOC-189 Removed TOC from CENM 1.2 deployment-kubernetes.md
  content/en/platform/corda/1.2/cenm/deployment-kubernetes.md
Labels: bug, documentation

#393 DOC-375 Removed misleading sentence about monitoring draining flows in node
  content/en/platform/corda/4.0/open-source/key-concepts-node.md
  content/en/platform/corda/4.1/open-source/key-concepts-node.md
  content/en/platform/corda/4.3/open-source/key-concepts-node.md
  content/en/platform/corda/4.4/open-source/key-concepts-node.md
  content/en/platform/corda/4.5/open-source/key-concepts-node.md
  content/en/platform/corda/4.6/open-source/key-concepts-node.md
  content/en/platform/corda/4.7/open-source/key-concepts-node.md
  content/en/platform/corda/4.8/open-source/key-concepts-node.md
Labels: bug, documentation

#395 DOC-172 Updated docker images for CENM 1.3-1.5
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
Labels: bug, documentation

#394 DOC-3368: OS 4.0 link fixes
  content/en/platform/corda/4.0/open-source/api-contract-constraints.md
  content/en/platform/corda/4.0/open-source/api-persistence.md
  content/en/platform/corda/4.0/open-source/api-scanner.md
  content/en/platform/corda/4.0/open-source/api-vault-query.md
  content/en/platform/corda/4.0/open-source/app-upgrade-notes.md
  content/en/platform/corda/4.0/open-source/aws-vm.md
  content/en/platform/corda/4.0/open-source/changelog.md
  content/en/platform/corda/4.0/open-source/cli-application-shell-extensions.md
  content/en/platform/corda/4.0/open-source/cli-ux-guidelines.md
  content/en/platform/corda/4.0/open-source/clientrpc.md
  content/en/platform/corda/4.0/open-source/contributing-philosophy.md
  content/en/platform/corda/4.0/open-source/contributing.md
  content/en/platform/corda/4.0/open-source/corda-api.md
  content/en/platform/corda/4.0/open-source/corda-configuration-file.md
  content/en/platform/corda/4.0/open-source/corda-network/the-corda-network.md
  content/en/platform/corda/4.0/open-source/cordapp-build-systems.md
  content/en/platform/corda/4.0/open-source/debugging-a-cordapp.md
  content/en/platform/corda/4.0/open-source/demobench.md
  content/en/platform/corda/4.0/open-source/deploying-a-node.md
  content/en/platform/corda/4.0/open-source/flow-state-machines.md
  content/en/platform/corda/4.0/open-source/getting-set-up.md
  content/en/platform/corda/4.0/open-source/hello-world-template.md
  content/en/platform/corda/4.0/open-source/json.md
  content/en/platform/corda/4.0/open-source/network-bootstrapper.md
  content/en/platform/corda/4.0/open-source/network-builder.md
  content/en/platform/corda/4.0/open-source/node-administration.md
  content/en/platform/corda/4.0/open-source/oracles.md
  content/en/platform/corda/4.0/open-source/quickstart-index.md
  content/en/platform/corda/4.0/open-source/running-a-node.md
  content/en/platform/corda/4.0/open-source/tutorial-tear-offs.md
  content/en/platform/corda/4.0/open-source/tutorial-test-dsl.md
  content/en/platform/corda/4.0/open-source/versioning.md
  content/en/platform/corda/4.1/open-source/running-a-node.md
Labels: bug, documentation

#397 DOC-1745 Corrected incorrect Corda docker image
  content/en/platform/corda/4.0/enterprise/docker-image.md
  content/en/platform/corda/4.1/enterprise/docker-image.md
  content/en/platform/corda/4.1/open-source/docker-image.md
  content/en/platform/corda/4.2/enterprise/docker-image.md
  content/en/platform/corda/4.3/enterprise/docker-image.md
  content/en/platform/corda/4.4/enterprise/docker-image.md
  content/en/platform/corda/4.5/enterprise/docker-image.md
  content/en/platform/corda/4.6/enterprise/docker-image.md
  content/en/platform/corda/4.7/enterprise/docker-image.md
  content/en/platform/corda/4.8/enterprise/docker-image.md
Labels: bug, documentation

#362 DOC-2255: Fix description of flowThreadPoolSize in Corda Configuration Field pages
  content/en/platform/corda/4.2/enterprise/corda-configuration-file.md
  content/en/platform/corda/4.3/enterprise/corda-configuration-file.md
  content/en/platform/corda/4.4/enterprise/node/setup/corda-configuration-file.md
  content/en/platform/corda/4.5/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/corda-configuration-fields.md
  content/en/platform/corda/4.6/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/corda-configuration-fields.md
  content/en/platform/corda/4.7/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/corda-configuration-fields.md
  content/en/platform/corda/4.8/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/corda-configuration-fields.md
Labels: bug, documentation, propagating changes

#399 DOC-2876: CRDB contradictory JBDC driver versions
  content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
Labels: bug, documentation

#400 DOC-83: Fix issues in highly-available notary metrics page
  content/en/platform/corda/4.1/enterprise/running-a-notary-cluster/notary-metrics.md
  content/en/platform/corda/4.2/enterprise/running-a-notary-cluster/notary-metrics.md
  content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/notary-metrics.md
  content/en/platform/corda/4.4/enterprise/notary/notary-metrics.md
  content/en/platform/corda/4.5/enterprise/notary/notary-metrics.md
  content/en/platform/corda/4.6/enterprise/notary/notary-metrics.md
  content/en/platform/corda/4.7/enterprise/notary/notary-metrics.md
  content/en/platform/corda/4.8/enterprise/notary/notary-metrics.md
Labels: bug, documentation, propagating changes

#404 DOC-213: Correct CENM log display command
  content/en/platform/corda/1.2/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes.md
Labels: bug, documentation, propagating changes

#402 DOC-2860 Added links to referenced pages
  content/en/platform/corda/4.1/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.2/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.3/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.3/open-source/checkpoint-tooling.md
  content/en/platform/corda/4.4/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.4/open-source/checkpoint-tooling.md
  content/en/platform/corda/4.5/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.5/open-source/checkpoint-tooling.md
  content/en/platform/corda/4.6/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.6/open-source/checkpoint-tooling.md
  content/en/platform/corda/4.7/enterprise/checkpoint-tooling.md
  content/en/platform/corda/4.7/open-source/checkpoint-tooling.md
  content/en/platform/corda/4.8/open-source/checkpoint-tooling.md
Labels: bug, documentation, don't merge yet

#396 DOC-126 Corrected standalone shell's config file format for user and password
  content/en/platform/corda/4.0/enterprise/shell.md
  content/en/platform/corda/4.0/open-source/shell.md
  content/en/platform/corda/4.1/enterprise/shell.md
  content/en/platform/corda/4.1/open-source/shell.md
  content/en/platform/corda/4.2/enterprise/shell.md
  content/en/platform/corda/4.3/enterprise/shell.md
  content/en/platform/corda/4.3/open-source/shell.md
  content/en/platform/corda/4.4/enterprise/node/operating/shell.md
  content/en/platform/corda/4.4/open-source/shell.md
  content/en/platform/corda/4.5/enterprise/node/operating/shell.md
  content/en/platform/corda/4.5/open-source/shell.md
  content/en/platform/corda/4.6/enterprise/node/operating/shell.md
  content/en/platform/corda/4.6/open-source/shell.md
  content/en/platform/corda/4.7/enterprise/node/operating/shell.md
  content/en/platform/corda/4.7/open-source/shell.md
  content/en/platform/corda/4.8/enterprise/node/operating/shell.md
  content/en/platform/corda/4.8/open-source/shell.md
Labels: bug, documentation

#407 DOC-2296: Adding `serviceLegalName` requirement to OS notary
  content/en/platform/corda/4.6/open-source/corda-configuration-fields.md
  content/en/platform/corda/4.7/open-source/corda-configuration-fields.md
  content/en/platform/corda/4.8/enterprise/node/operating/node-database-tables.md
  content/en/platform/corda/4.8/open-source/corda-configuration-fields.md
Labels: bug, documentation, propagating changes

#401 DOC-233 Removed Corda version number re: hotswapping of network parameters
  content/en/platform/corda/1.3/cenm/updating-network-parameters.md
  content/en/platform/corda/1.4/cenm/updating-network-parameters.md
  content/en/platform/corda/1.5/cenm/updating-network-parameters.md
Labels: bug, documentation

#406 DOC-3662 Updated build script for the Azure Key Vault HSM driver.
  content/en/platform/corda/4.8/enterprise/node/operating/cryptoservice-configuration.md
Labels: bug, documentation

#410 DOC-1758 Corrected typo in Configuring a JPA notary backend, database setup section
  content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/installing-jpa.md
  content/en/platform/corda/4.4/enterprise/notary/installing-jpa.md
  content/en/platform/corda/4.5/enterprise/notary/installing-jpa.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.6/enterprise/notary/installing-jpa.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.7/enterprise/notary/installing-jpa.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.8/enterprise/notary/installing-jpa.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
Labels: bug, documentation

#408 DOC-528: Added Azure SQL to CENM databases lists.
  content/en/platform/corda/1.3/cenm/cenm-support-matrix.md
  content/en/platform/corda/1.3/cenm/database-set-up.md
  content/en/platform/corda/1.4/cenm/cenm-support-matrix.md
  content/en/platform/corda/1.4/cenm/database-set-up.md
  content/en/platform/corda/1.5/cenm/cenm-support-matrix.md
  content/en/platform/corda/1.5/cenm/database-set-up.md
Labels: bug, documentation

#388 DOC-171: Corrected HSM CI code snippet. Made note that native does not require…
  content/en/platform/corda/4.7/enterprise/node/operating/confidential-identities-hsm.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/hsm-deployment-confidential.md
  content/en/platform/corda/4.8/enterprise/node/operating/confidential-identities-hsm.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/hsm-deployment-confidential.md
Labels: bug, documentation

#411 DOC-558: Checked Azure Key Vault spelling and corrected where needed
  content/en/api-ref/corda/1.2/cenm/javadoc/com/r3/corda/networkmanage/common/cryptoservice/azurekeyvault/AzureKeyVaultCryptoService.html
  content/en/api-ref/corda/1.2/cenm/kotlin/corda/com.r3.corda.networkmanage.common.cryptoservice.azurekeyvault/-azure-key-vault-crypto-service/-init-.html
  content/en/api-ref/corda/1.2/cenm/kotlin/corda/com.r3.corda.networkmanage.common.cryptoservice.azurekeyvault/-azure-key-vault-crypto-service/index.html
  content/en/api-ref/corda/1.3/cenm/javadoc/com/r3/corda/networkmanage/common/cryptoservice/azurekeyvault/AzureKeyVaultCryptoService.html
  content/en/api-ref/corda/1.3/cenm/kotlin/corda/com.r3.corda.networkmanage.common.cryptoservice.azurekeyvault/-azure-key-vault-crypto-service/-init-.html
  content/en/api-ref/corda/1.3/cenm/kotlin/corda/com.r3.corda.networkmanage.common.cryptoservice.azurekeyvault/-azure-key-vault-crypto-service/index.html
  content/en/api-ref/corda/1.4/cenm/javadoc/com/r3/corda/networkmanage/common/cryptoservice/azurekeyvault/AzureKeyVaultCryptoService.html
  content/en/api-ref/corda/1.4/cenm/kotlin/corda/com.r3.corda.networkmanage.common.cryptoservice.azurekeyvault/-azure-key-vault-crypto-service/-init-.html
  content/en/api-ref/corda/1.4/cenm/kotlin/corda/com.r3.corda.networkmanage.common.cryptoservice.azurekeyvault/-azure-key-vault-crypto-service/index.html
  content/en/api-ref/corda/1.5/cenm/javadoc/com/r3/corda/networkmanage/common/cryptoservice/azurekeyvault/AzureKeyVaultCryptoService.html
  content/en/api-ref/corda/1.5/cenm/kotlin/corda/com.r3.corda.networkmanage.common.cryptoservice.azurekeyvault/-azure-key-vault-crypto-service/-init-.html
  content/en/api-ref/corda/1.5/cenm/kotlin/corda/com.r3.corda.networkmanage.common.cryptoservice.azurekeyvault/-azure-key-vault-crypto-service/index.html
  content/en/platform/corda/4.0/enterprise/cryptoservice-configuration.md
  content/en/platform/corda/4.1/enterprise/cryptoservice-configuration.md
  content/en/platform/corda/4.2/enterprise/cryptoservice-configuration.md
  content/en/platform/corda/4.3/enterprise/cryptoservice-configuration.md
  content/en/platform/corda/4.3/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.4/enterprise/node/operating/cryptoservice-configuration.md
  content/en/platform/corda/4.5/enterprise/node/operating/cryptoservice-configuration.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/hsm-deployment.md
  content/en/platform/corda/4.6/enterprise/node/operating/cryptoservice-configuration.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/hsm-deployment.md
  content/en/platform/corda/4.7/enterprise/node/operating/cryptoservice-configuration.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/hsm-deployment.md
  content/en/platform/corda/4.7/enterprise/release-notes-enterprise-ja.md
  content/en/platform/corda/4.7/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.8/enterprise/node/operating/cryptoservice-configuration.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/hsm-deployment.md
Labels: bug, documentation

#415 DOC-524 remove reference to packageOwnership
  content/en/platform/corda/1.0/cenm/network-map.md
  content/en/platform/corda/1.1/cenm/network-map.md
  content/en/platform/corda/1.2/cenm/network-map.md
  content/en/platform/corda/1.3/cenm/network-map.md
  content/en/platform/corda/1.4/cenm/network-map.md
  content/en/platform/corda/1.5/cenm/network-map.md
Labels: bug

#418 DOC-463: Updated the CENM 1.3, 1.4 and 1.5 deployment-kubernetes.md file with a correct link
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
Labels: bug, documentation
