Repository corda/corda-docs-portal, pull requests merged in 2021-12, with the labels that each got.

#414 DOC-433 Propagated code snippets from OS to ENT for API:testing
  content/en/platform/corda/4.4/enterprise/cordapps/api-testing.md
  content/en/platform/corda/4.5/enterprise/cordapps/api-testing.md
  content/en/platform/corda/4.6/enterprise/cordapps/api-testing.md
  content/en/platform/corda/4.7/enterprise/cordapps/api-testing.md
  content/en/platform/corda/4.8/enterprise/cordapps/api-testing.md
Labels: bug, documentation

#420 DOC-378 Updated notary registration tool to HA Utilities tool.
  content/en/platform/corda/4.4/enterprise/corda-network/setup-segregated-notary.md
  content/en/platform/corda/4.4/enterprise/ha-utilities.md
  content/en/platform/corda/4.4/enterprise/notary/ha-notary-service-setup.md
  content/en/platform/corda/4.4/enterprise/notary/hsm-support.md
  content/en/platform/corda/4.5/enterprise/corda-network/setup-segregated-notary.md
  content/en/platform/corda/4.5/enterprise/ha-utilities.md
  content/en/platform/corda/4.5/enterprise/notary/ha-notary-service-setup.md
  content/en/platform/corda/4.5/enterprise/notary/hsm-support.md
  content/en/platform/corda/4.6/enterprise/corda-network/setup-segregated-notary.md
  content/en/platform/corda/4.6/enterprise/ha-utilities.md
  content/en/platform/corda/4.6/enterprise/notary/ha-notary-service-setup.md
  content/en/platform/corda/4.6/enterprise/notary/hsm-support.md
  content/en/platform/corda/4.7/enterprise/corda-network/setup-segregated-notary.md
  content/en/platform/corda/4.7/enterprise/ha-utilities.md
  content/en/platform/corda/4.7/enterprise/notary/ha-notary-service-setup.md
  content/en/platform/corda/4.7/enterprise/notary/hsm-support.md
  content/en/platform/corda/4.8/enterprise/corda-network/setup-segregated-notary.md
  content/en/platform/corda/4.8/enterprise/ha-utilities.md
  content/en/platform/corda/4.8/enterprise/notary/ha-notary-service-setup.md
  content/en/platform/corda/4.8/enterprise/notary/hsm-support.md
Labels: bug, documentation

#416 DOC-292 change dataSource.user field for Oracle setups and clairfy MY…
  content/en/platform/corda/4.3/enterprise/node-database-admin.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.5/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.6/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.7/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.8/enterprise/node/operating/node-database-admin.md
Labels: bug

#344 DOC-3599: Make improvements to Mission Mars - write states
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-contract.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-intro.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-state-2.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-state.md
Labels: documentation, dev preview, tutorials

#421 DOC-2271: Changing custom Java query code sample on `api-vault-query`
  content/en/platform/corda/4.1/enterprise/api-vault-query.md
  content/en/platform/corda/4.2/enterprise/api-vault-query.md
  content/en/platform/corda/4.3/enterprise/api-vault-query.md
  content/en/platform/corda/4.4/enterprise/cordapps/api-vault-query.md
  content/en/platform/corda/4.5/enterprise/cordapps/api-vault-query.md
  content/en/platform/corda/4.6/enterprise/cordapps/api-vault-query.md
  content/en/platform/corda/4.7/enterprise/cordapps/api-vault-query.md
  content/en/platform/corda/4.8/enterprise/cordapps/api-vault-query.md
Labels: bug, propagating changes

#423 DOC-1831 Removed obsolete DOCSTART and DOCEND tags from code examples
  content/en/platform/corda/4.0/enterprise/flow-cookbook.md
  content/en/platform/corda/4.0/enterprise/flow-state-machines.md
  content/en/platform/corda/4.0/enterprise/tut-two-party-flow.md
  content/en/platform/corda/4.0/enterprise/tutorial-clientrpc-api.md
  content/en/platform/corda/4.0/open-source/flow-cookbook.md
  content/en/platform/corda/4.0/open-source/tut-two-party-flow.md
  content/en/platform/corda/4.0/open-source/tutorial-clientrpc-api.md
  content/en/platform/corda/4.1/enterprise/flow-cookbook.md
  content/en/platform/corda/4.1/enterprise/flow-state-machines.md
  content/en/platform/corda/4.1/enterprise/tutorial-clientrpc-api.md
  content/en/platform/corda/4.1/open-source/flow-cookbook.md
  content/en/platform/corda/4.1/open-source/flow-state-machines.md
  content/en/platform/corda/4.1/open-source/tutorial-clientrpc-api.md
  content/en/platform/corda/4.2/enterprise/flow-cookbook.md
  content/en/platform/corda/4.2/enterprise/flow-state-machines.md
  content/en/platform/corda/4.2/enterprise/tutorial-clientrpc-api.md
  content/en/platform/corda/4.3/enterprise/flow-cookbook.md
  content/en/platform/corda/4.3/enterprise/flow-state-machines.md
  content/en/platform/corda/4.3/enterprise/tutorial-clientrpc-api.md
  content/en/platform/corda/4.3/open-source/flow-cookbook.md
  content/en/platform/corda/4.3/open-source/flow-state-machines.md
  content/en/platform/corda/4.3/open-source/tutorial-clientrpc-api.md
  content/en/platform/corda/4.4/enterprise/cordapps/flow-cookbook.md
  content/en/platform/corda/4.4/enterprise/flow-state-machines.md
  content/en/platform/corda/4.4/open-source/flow-cookbook.md
  content/en/platform/corda/4.4/open-source/flow-state-machines.md
  content/en/platform/corda/4.4/open-source/tutorial-clientrpc-api.md
  content/en/platform/corda/4.5/enterprise/cordapps/flow-cookbook.md
  content/en/platform/corda/4.5/enterprise/flow-state-machines.md
  content/en/platform/corda/4.5/open-source/flow-cookbook.md
  content/en/platform/corda/4.5/open-source/flow-state-machines.md
  content/en/platform/corda/4.5/open-source/tutorial-clientrpc-api.md
  content/en/platform/corda/4.6/enterprise/cordapps/flow-cookbook.md
  content/en/platform/corda/4.6/enterprise/flow-state-machines.md
  content/en/platform/corda/4.6/open-source/flow-cookbook.md
  content/en/platform/corda/4.6/open-source/flow-state-machines.md
  content/en/platform/corda/4.6/open-source/tutorial-clientrpc-api.md
  content/en/platform/corda/4.7/enterprise/cordapps/flow-cookbook.md
  content/en/platform/corda/4.7/enterprise/flow-state-machines.md
  content/en/platform/corda/4.7/open-source/flow-cookbook.md
  content/en/platform/corda/4.7/open-source/flow-state-machines.md
  content/en/platform/corda/4.7/open-source/tutorial-clientrpc-api.md
  content/en/platform/corda/4.8/enterprise/cordapps/flow-cookbook.md
  content/en/platform/corda/4.8/enterprise/flow-state-machines.md
  content/en/platform/corda/4.8/open-source/flow-cookbook.md
  content/en/tutorials/corda/4.8/os/supplementary-tutorials/tutorial-clientrpc-api.md
Labels: bug, documentation

#426 DOC-1789 Typo corrected in signing service CENM 1.1
  content/en/platform/corda/1.1/cenm/signing-service.md
Labels: bug, documentation

#427 DOC-157 Defined AKS
  content/en/platform/corda/4.4/enterprise/release-notes-enterprise.md
Labels: bug, documentation

#422 DOC-228 Updated node database table
  content/en/platform/corda/4.4/enterprise/node/operating/node-database.md
  content/en/platform/corda/4.5/enterprise/node/operating/node-database.md
  content/en/platform/corda/4.6/enterprise/node/operating/node-database.md
  content/en/platform/corda/4.7/enterprise/node/operating/node-database.md
  content/en/platform/corda/4.8/enterprise/node/operating/node-database.md
Labels: bug, documentation

#419 DOC-543: Clarified info on BNO responsibilities in private network.
  content/en/platform/corda/4.5/enterprise/operations/project-planner/network-operators.md
  content/en/platform/corda/4.6/enterprise/operations/project-planner/network-operators.md
  content/en/platform/corda/4.7/enterprise/operations/project-planner/network-operators.md
  content/en/platform/corda/4.8/enterprise/operations/project-planner/network-operators.md
Labels: bug, documentation, waiting for SME review

#429 DOC-547: Added link to Azure Key Vault documentation.
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
Labels: documentation, enhancement

#430 DOC-2019: Fixed broken table.
  content/en/platform/corda/1.1/cenm/network-map-overview.md
  content/en/platform/corda/1.2/cenm/network-map-overview.md
  content/en/platform/corda/1.3/cenm/network-map-overview.md
  content/en/platform/corda/1.4/cenm/network-map-overview.md
  content/en/platform/corda/1.5/cenm/network-map-overview.md
Labels: bug, documentation

#431 DOC-405: Fixed broken table.
  content/en/platform/corda/1.1/cenm/pki-tool.md
  content/en/platform/corda/1.2/cenm/pki-tool.md
  content/en/platform/corda/1.3/cenm/pki-tool.md
  content/en/platform/corda/1.4/cenm/pki-tool.md
  content/en/platform/corda/1.5/cenm/pki-tool.md
Labels: bug, documentation

#428 DOC-393 Updated create storage class and namespace guide
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes.md
Labels: bug, documentation

#433 DOC-59: Removed confusing/inaccurate diagram.
  content/en/platform/corda/4.4/enterprise/cordapps/api-transactions.md
  content/en/platform/corda/4.4/open-source/api-transactions.md
  content/en/platform/corda/4.5/enterprise/cordapps/api-transactions.md
  content/en/platform/corda/4.5/open-source/api-transactions.md
  content/en/platform/corda/4.6/enterprise/cordapps/api-transactions.md
  content/en/platform/corda/4.6/open-source/api-transactions.md
  content/en/platform/corda/4.7/enterprise/cordapps/api-transactions.md
  content/en/platform/corda/4.7/open-source/api-transactions.md
  content/en/platform/corda/4.8/enterprise/cordapps/api-transactions.md
  content/en/platform/corda/4.8/open-source/api-transactions.md
Labels: bug, documentation

#432 DOC-488: Fixed list indentation.
  content/en/platform/corda/4.6/enterprise/network/joining-a-compatibility-zone.md
  content/en/platform/corda/4.6/open-source/joining-a-compatibility-zone.md
  content/en/platform/corda/4.7/enterprise/network/joining-a-compatibility-zone.md
  content/en/platform/corda/4.7/open-source/joining-a-compatibility-zone.md
  content/en/platform/corda/4.8/enterprise/network/joining-a-compatibility-zone.md
  content/en/platform/corda/4.8/open-source/joining-a-compatibility-zone.md
Labels: bug, documentation

#425 DOC-322 Removed references to READ_COMMITTED
  content/en/platform/corda/4.6/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.6/enterprise/node/operating/node-database-developer.md
  content/en/platform/corda/4.6/enterprise/notary/db-guidelines.md
  content/en/platform/corda/4.6/enterprise/performance-testing/r3-performance-runs.md
  content/en/platform/corda/4.6/enterprise/resources/node.conf
  content/en/platform/corda/4.7/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.7/enterprise/node/operating/node-database-developer.md
  content/en/platform/corda/4.7/enterprise/notary/db-guidelines.md
  content/en/platform/corda/4.7/enterprise/performance-testing/r3-performance-runs.md
  content/en/platform/corda/4.7/enterprise/resources/node.conf
  content/en/platform/corda/4.8/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.8/enterprise/node/operating/node-database-developer.md
  content/en/platform/corda/4.8/enterprise/notary/db-guidelines.md
  content/en/platform/corda/4.8/enterprise/performance-testing/r3-performance-runs.md
  content/en/platform/corda/4.8/enterprise/resources/node.conf
  content/en/platform/corda/4.8/open-source/resources/node.conf
Labels: bug, documentation

#434 DOC-3630: Make clear that notary entries in network map are immutable.
  content/en/platform/corda/4.6/enterprise/network/network-map.md
  content/en/platform/corda/4.6/open-source/network-map.md
  content/en/platform/corda/4.7/enterprise/network/network-map.md
  content/en/platform/corda/4.7/open-source/network-map.md
  content/en/platform/corda/4.8/enterprise/network/network-map.md
  content/en/platform/corda/4.8/open-source/network-map.md
Labels: documentation, enhancement

#435 DOC-1848: Add `DatabaseRetry` to notary metrics table
  content/en/platform/corda/4.6/enterprise/notary/notary-metrics.md
  content/en/platform/corda/4.7/enterprise/notary/notary-metrics.md
  content/en/platform/corda/4.8/enterprise/notary/notary-metrics.md
Labels: bug, documentation

#438 DOC-2025 Fixed typo and other minor errors in PKI guide.
  content/en/platform/corda/1.3/cenm/pki-guide.md
  content/en/platform/corda/1.4/cenm/pki-guide.md
  content/en/platform/corda/1.5/cenm/pki-guide.md
  content/en/platform/corda/4.4/enterprise/node/pki-guide.md
  content/en/platform/corda/4.5/enterprise/node/pki-guide.md
  content/en/platform/corda/4.6/enterprise/node/pki-guide.md
  content/en/platform/corda/4.7/enterprise/node/pki-guide.md
  content/en/platform/corda/4.8/enterprise/node/pki-guide.md
Labels: bug, documentation

#436 DOC-465 Updated config samples for pki and signing service.
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
Labels: bug, documentation

#412 DOC-2055 Corrected reference to flow management console in flow hospital.
  content/en/platform/corda/4.7/enterprise/node/node-flow-hospital.md
  content/en/platform/corda/4.7/open-source/node-flow-hospital.md
  content/en/platform/corda/4.8/enterprise/node/node-flow-hospital.md
  content/en/platform/corda/4.8/open-source/node-flow-hospital.md
Labels: bug, documentation

#439 DOC-560: Added note on IE 11 not being supported for CENM UIs.
  content/en/platform/corda/1.5/cenm/cenm-console.md
  content/en/platform/corda/1.5/cenm/user-admin.md
Labels: bug, documentation

#440 DOC-223: Corrected indentation and outdated steps.
  content/en/platform/corda/4.4/open-source/contributing.md
  content/en/platform/corda/4.5/open-source/contributing.md
  content/en/platform/corda/4.6/open-source/contributing.md
  content/en/platform/corda/4.7/open-source/contributing.md
  content/en/platform/corda/4.8/open-source/contributing.md
Labels: bug, documentation

#443 DOC-1984 Fixed Azure client jar build steps
  content/en/platform/corda/4.7/enterprise/node/operating/cryptoservice-configuration.md
Labels: bug, documentation

#444 DOC-2135: Note - not possible to reconfigure existing non-validating notary into validating one
  content/en/platform/corda/4.8/enterprise/operations/deployment/corda-configuration-fields.md
Labels: bug, documentation

#445 DOC-3556 Fixed contradicting information about runMigration/initialiseSchema
  content/en/platform/corda/4.2/enterprise/corda-configuration-file.md
  content/en/platform/corda/4.3/enterprise/corda-configuration-file.md
  content/en/platform/corda/4.3/open-source/corda-configuration-file.md
  content/en/platform/corda/4.4/enterprise/node/setup/corda-configuration-file.md
  content/en/platform/corda/4.5/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/corda-configuration-fields.md
Labels: bug, documentation

#441 DOC-3451: Notary Database setup docs inconsistencies
  content/en/platform/corda/4.8/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
Labels: bug, documentation

#446 DOC-468: Node deployment diagram bulletpoints -> numbers
  content/en/platform/corda/4.4/enterprise/node/component-topology.md
  content/en/platform/corda/4.5/enterprise/node/component-topology.md
  content/en/platform/corda/4.6/enterprise/node/component-topology.md
  content/en/platform/corda/4.6/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.7/enterprise/node/component-topology.md
  content/en/platform/corda/4.8/enterprise/tools-config-obfuscator.md
Labels: bug, documentation

#366 DOC-3617 Corda Payments
  content/en/apps/_index.md
  content/en/apps/bankinabox/bank-index.md
  content/en/apps/payments/payment-service-flows.md
  content/en/apps/payments/payments-agent.md
  content/en/apps/payments/payments-index.md
  content/en/apps/payments/payments-sdk.md
  content/en/apps/payments/send-payments.md
Labels: don't merge yet

#455 DOC-3721-1 add announcement banner to docs site
  themes/doks/layouts/partials/header/header.html
Labels: enhancement, theme

#459 DOC-3738 Add release notes for Corda 4.8.5
  content/en/platform/corda/4.8/enterprise/legal-info-4.8.5.md
  content/en/platform/corda/4.8/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.8/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.8/open-source/release-notes.md
Labels: documentation

#460 DOC-3739: Add release notes for Corda 4.6.7 OS + CE.
  content/en/platform/corda/4.6/enterprise/legal-info-4.6.7.md
  content/en/platform/corda/4.6/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.6/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.6/open-source/release-notes.md
Labels: documentation

#461 DOC-3728 Add release notes for Corda 4.7.5
  content/en/platform/corda/4.7/enterprise/legal-info-4.7.5.md
  content/en/platform/corda/4.7/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.7/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.7/open-source/release-notes.md
Labels: release

#466 DOC-3740 Added supported details to release notes.
  content/en/platform/corda/4.6/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.7/enterprise/legal-info-4.7.1.md
  content/en/platform/corda/4.7/enterprise/legal-info-4.7.2.md
  content/en/platform/corda/4.7/enterprise/legal-info-4.7.3.md
  content/en/platform/corda/4.7/enterprise/legal-info-4.7.5.md
  content/en/platform/corda/4.7/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.8/enterprise/release-notes-enterprise.md
Labels: release

#467 DOC-3740-1 Updated legal info header
  content/en/platform/corda/4.6/enterprise/legal-info-4.6.6.md
  content/en/platform/corda/4.6/enterprise/legal-info-4.6.7.md
  content/en/platform/corda/4.7/enterprise/legal-info-4.7.5.md
Labels: bug

#464 DOC-3729 legal info and checksums 4.4.10 patch
  content/en/platform/corda/4.4/enterprise/legal-info-4.4.10.md
  content/en/platform/corda/4.4/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.4/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.4/open-source/release-notes.md
Labels: release

#465 DOC-3727: Log4j CE 4.5.8 update
  content/en/platform/corda/4.5/enterprise/legal-info-4.5.8.md
  content/en/platform/corda/4.5/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.5/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.5/open-source/release-notes.md
Labels: release

#463 DOC-3730: Added release notes for Corda 4.3.10 OS + CE.
  content/en/platform/corda/4.3/enterprise/legal-info-4.3.10.md
  content/en/platform/corda/4.3/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.3/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.3/open-source/release-notes.md
Labels: don't merge yet, release

#472 DOC-3731 Added release note for CENM 1.2.5.
  content/en/platform/corda/1.2/cenm/legal-info-1.2.5.md
  content/en/platform/corda/1.2/cenm/release-checksum-cenm.md
  content/en/platform/corda/1.2/cenm/release-notes.md
Labels: release

#477 DOC-3733: Added release notes for CENM 1.3.4 patch release.
  content/en/platform/corda/1.3/cenm/legal-info-1.3.4.md
  content/en/platform/corda/1.3/cenm/release-checksum-cenm.md
  content/en/platform/corda/1.3/cenm/release-notes.md
Labels: release

#478 Doc 3750 Updates to the Log4j release schedule
  content/en/release-notes/_index.md
Labels: release

#473 DOC-3732 Added release note for CENM 1.5.3.
  content/en/platform/corda/1.5/cenm/legal-info-1.5.3.md
  content/en/platform/corda/1.5/cenm/release-checksum-cenm.md
  content/en/platform/corda/1.5/cenm/release-notes.md
Labels: release

#480 DOC-3753: Dec 21 noon alerts page update.
  content/en/release-notes/_index.md
Labels: release

#481 DOC-3751 Added note about Log4j dependency to CENM management console
  content/en/platform/corda/1.5/cenm/cenm-console.md
Labels: release

#487 DOC-3756 Updated legal file for Payments.
  content/en/apps/payments/payments-legal-info.md
Labels: documentation

#479 DOC-3734: Added release notes for CENM 1.4.3 patch release.
  content/en/platform/corda/1.4/cenm/legal-info-1.4.3.md
  content/en/platform/corda/1.4/cenm/release-checksum-cenm.md
  content/en/platform/corda/1.4/cenm/release-notes.md
  content/en/release-notes/_index.md
Labels: release

#491 DOC-3748 Added note about Log4j dependency to node management console.
  content/en/platform/corda/4.7/enterprise/node/management-console/index.md
  content/en/platform/corda/4.8/enterprise/node/management-console/index.md
  content/en/release-notes/_index.md
Labels: release

#490 DOC-3746 Added release notes for Log4j to business network membership.
  content/en/platform/corda/4.6/open-source/business-network-membership.md
  content/en/release-notes/_index.md
Labels: release

#494 DOC-3758 DOC-3421: Fixed broken link. Added missing steps to start shell. Removed badly propagated section.
  content/en/platform/corda/4.3/enterprise/shell.md
  content/en/platform/corda/4.3/open-source/shell.md
  content/en/platform/corda/4.4/enterprise/node/operating/shell.md
  content/en/platform/corda/4.4/open-source/shell.md
  content/en/platform/corda/4.5/enterprise/node/operating/shell.md
  content/en/platform/corda/4.5/open-source/shell.md
  content/en/platform/corda/4.6/enterprise/node/operating/shell.md
  content/en/platform/corda/4.6/open-source/shell.md
  content/en/platform/corda/4.7/enterprise/node/operating/shell.md
  content/en/platform/corda/4.7/open-source/shell.md
  content/en/platform/corda/4.8/enterprise/node/operating/shell.md
  content/en/platform/corda/4.8/open-source/shell.md
Labels: bug

#495 DOC-3759: Added minimum Docker version to Corda CLI install doc.
  content/en/platform/corda/5.0-dev-preview-1/corda-cli/installing-corda-cli.md
  content/en/platform/corda/5.0-dev-preview-1/getting-started/overview.md
Labels: bug, dev preview
