Repository corda/corda-docs-portal, pull requests merged in 2022-05, with the labels that each got.

#621 DOC-3934 - 4.9.1 patch release
  content/en/platform/corda/4.9/community/release-checksum-os.md
  content/en/platform/corda/4.9/community/release-notes.md
  content/en/platform/corda/4.9/community/release-platform-support-matrix.md
  content/en/platform/corda/4.9/enterprise/platform-support-matrix.md
  content/en/platform/corda/4.9/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.9/enterprise/release-notes-enterprise.md
Labels: release, community edition

#620 D0C-71: PKI Tool from CENM found in Enterprise CE4.4 Tool dropdown
  config/_default/menus/menus.en.toml
  content/en/platform/corda/1.0/cenm/shell.md
  content/en/platform/corda/1.0/cenm/tools-index.md
  content/en/platform/corda/1.1/cenm/shell.md
  content/en/platform/corda/1.1/cenm/tools-index.md
  content/en/platform/corda/1.2/cenm/shell.md
  content/en/platform/corda/1.2/cenm/tools-index.md
  content/en/platform/corda/1.3/cenm/shell.md
  content/en/platform/corda/1.3/cenm/tools-index.md
  content/en/platform/corda/1.4/cenm/shell.md
  content/en/platform/corda/1.4/cenm/tools-index.md
  content/en/platform/corda/4.6/enterprise/pki-tool.md
  content/en/platform/corda/4.7/enterprise/pki-tool.md
  content/en/platform/corda/4.8/enterprise/pki-tool.md
  content/en/platform/corda/4.9/enterprise/pki-tool.md
Labels: bug

#623 DOC-3981: Version numbers update for CockroachDB
  content/en/platform/corda/4.8/enterprise/notary/installing-jpa.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.8/enterprise/operations/project-planner/network-operators.md
  content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
  content/en/platform/corda/4.9/enterprise/node/deploy/platform-support-matrix.md
  content/en/platform/corda/4.9/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.9/enterprise/platform-support-matrix.md
Labels: dependencies
