Repository corda/corda-docs-portal, pull requests merged in 2022-02, with the labels that each got.

#540 DOC-3776-1 Patch release: log4j v2.17.1 docs update Part II
  content/en/platform/corda/1.2/cenm/legal-info-1.2.6.md
  content/en/platform/corda/1.2/cenm/release-checksum-cenm.md
  content/en/platform/corda/1.2/cenm/release-notes.md
  content/en/platform/corda/1.3/cenm/legal-info-1.3.5.md
  content/en/platform/corda/1.3/cenm/release-checksum-cenm.md
  content/en/platform/corda/1.3/cenm/release-notes.md
  content/en/platform/corda/1.4/cenm/legal-info-1.4.4.md
  content/en/platform/corda/1.4/cenm/release-checksum-cenm.md
  content/en/platform/corda/1.4/cenm/release-notes.md
  content/en/platform/corda/1.5/cenm/legal-info-1.5.4.md
  content/en/platform/corda/1.5/cenm/release-checksum-cenm.md
  content/en/platform/corda/1.5/cenm/release-notes.md
  content/en/platform/corda/4.8/enterprise/release-notes-enterprise.md
  content/en/platform/corda/5.0-dev-preview-1/release-notes-c5dp1.md
  content/en/release-notes/_index.md
Labels: don't merge yet, release

#549 DOC-177: Added a note about best CENM deployment performance when using k8s
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
Labels: bug, waiting for SME review

#546 DOC-3816 update key concept page oracles
  content/en/platform/corda/4.8/open-source/key-concepts-oracles.md
Labels: community edition

#552 DOC-3811 update key concepts contracts
  content/en/platform/corda/4.8/open-source/key-concepts-contracts.md
Labels: community edition

#551 DOC-3813 update key concepts consensus
  content/en/platform/corda/4.8/open-source/key-concepts-consensus.md
Labels: community edition

#553 DOC-570: Added link to defined country codes.
  content/en/platform/corda/4.5/enterprise/node/setup/node-naming.md
  content/en/platform/corda/4.5/open-source/node-naming.md
  content/en/platform/corda/4.6/enterprise/node/setup/node-naming.md
  content/en/platform/corda/4.6/open-source/node-naming.md
  content/en/platform/corda/4.7/enterprise/node/setup/node-naming.md
  content/en/platform/corda/4.7/open-source/node-naming.md
  content/en/platform/corda/4.8/enterprise/node/setup/node-naming.md
  content/en/platform/corda/4.8/open-source/node-naming.md
Labels: bug

#554 DOC-346: Corrected configuration parameter.
  content/en/platform/corda/4.4/enterprise/node/setup/corda-configuration-file.md
  content/en/platform/corda/4.5/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.6/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.7/enterprise/node/setup/corda-configuration-fields.md
  content/en/platform/corda/4.8/enterprise/node/setup/corda-configuration-fields.md
Labels: bug

#543 DOC-3814: Key concepts - notaries
  content/en/platform/corda/4.8/open-source/key-concepts-notaries.md
Labels: release, community edition

#548 DOC-3857 Patch release CE4.8.6
  content/en/platform/corda/4.8/enterprise/legal-info-4.8.6.md
  content/en/platform/corda/4.8/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.8/enterprise/release-notes-enterprise.md
  content/en/release-notes/_index.md
Labels: release

#557 DOC-3868 Updates to CE4.8.6 to republish
  content/en/platform/corda/4.8/enterprise/legal-info-4.8.6.md
  content/en/platform/corda/4.8/enterprise/release-checksum-enterprise.md
  content/en/platform/corda/4.8/enterprise/release-notes-enterprise.md
  content/en/release-notes/_index.md
Labels: bug

#558 DOC-3792 Patch release Corda 5 DP 1.0.1 release notes
  content/en/platform/corda/5.0-dev-preview-1/getting-started/overview.md
  content/en/platform/corda/5.0-dev-preview-1/legal-info/corda-5-dev-preview.md
  content/en/platform/corda/5.0-dev-preview-1/legal-info/corda-cli.md
  content/en/platform/corda/5.0-dev-preview-1/nodes/operating/cli-curl/cli-curl.md
  content/en/platform/corda/5.0-dev-preview-1/packaging/cordapp-builder.md
  content/en/platform/corda/5.0-dev-preview-1/release-checksums-c5dp1.md
  content/en/platform/corda/5.0-dev-preview-1/release-notes-c5dp1.md
  content/en/release-notes/_index.md
Labels: release

#562 DOC-3812 Updated key concepts flows.
  content/en/platform/corda/4.8/open-source/key-concepts-flows.md
Labels: community edition

#547 DOC-3815: Key concepts - time-windows
  content/en/platform/corda/4.8/open-source/key-concepts-time-windows.md
Labels: community edition

#555 DOC-3818 update key concepts transaction tear-offs
  content/en/platform/corda/4.8/open-source/key-concepts-tearoffs.md
Labels: community edition

#542 DOC-3808 Update key concept page Ledger
  content/en/platform/corda/4.8/open-source/key-concepts-ledger.md
Labels: community edition

#560 DOC-3809 Updated key concepts states
  content/en/platform/corda/4.8/open-source/key-concepts-states.md
Labels: community edition

#565 DOC-3881: Typo in CLI DP doc
  content/en/platform/corda/5.0-dev-preview-1/corda-cli/commands.md
Labels: bug

#566 DOC-3878-1 Reinstated release notes for OS 4.3
  content/en/platform/corda/4.3/open-source/release-notes.md
  content/en/release-notes/_index.md
Labels: bug

#567 DOC-3863 Added note to certificate rotation functionality.
  content/en/platform/corda/1.5/cenm/release-notes.md
  content/en/platform/corda/1.5/cenm/tools-index.md
  content/en/platform/corda/4.7/enterprise/ha-utilities.md
  content/en/platform/corda/4.7/enterprise/release-notes-enterprise.md
  content/en/platform/corda/4.8/enterprise/ha-utilities.md
Labels: bug

#568 DOC-3798 update key concepts intro page and add webinar page
  content/en/platform/corda/4.8/open-source/key-concepts-ecosystem.md
  content/en/platform/corda/4.8/open-source/key-concepts-webinars.md
  content/en/platform/corda/4.8/open-source/key-concepts.md
  themes/doks/layouts/index.html
Labels: community edition

#569 DOC-3895: Added code and note about using Mockito to create mock party instances
  content/en/platform/corda/5.0-dev-preview-1/cordapps/ledger-dsl.md
Labels: bug, don't merge yet, waiting for SME review

#571 DOC-1913 update versions in node-upgrade-notes
  content/en/platform/corda/4.1/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.2/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.2/enterprise/operating/cm-upgrading-node.md
  content/en/platform/corda/4.3/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.4/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.4/enterprise/node/operating/cm-upgrading-node.md
  content/en/platform/corda/4.5/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.5/enterprise/node/operating/cm-upgrading-node.md
  content/en/platform/corda/4.6/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.7/enterprise/node-upgrade-notes.md
Labels: bug

#572 DOC-249: Updated the CENM corda-network file
  content/en/platform/corda/1.2/cenm/corda-networks.md
  content/en/platform/corda/1.3/cenm/corda-networks.md
  content/en/platform/corda/1.4/cenm/corda-networks.md
  content/en/platform/corda/1.5/cenm/corda-networks.md
Labels: bug, waiting for SME review

#564 DOC-3878 Added instructions on how to download latest version of OS4.8
  content/en/platform/corda/4.8/open-source/release-notes.md
Labels: bug

#573 DOC-3897 Added instructions on how to build OS
  content/en/platform/corda/4.3/open-source/release-notes.md
  content/en/platform/corda/4.4/open-source/release-notes.md
  content/en/platform/corda/4.5/open-source/release-notes.md
  content/en/platform/corda/4.6/open-source/release-notes.md
  content/en/platform/corda/4.7/open-source/release-notes.md
  content/en/platform/corda/4.8/open-source/release-notes.md
Labels: bug

#574 DOC-3871: Postgres version support update
  content/en/platform/corda/4.8/enterprise/operations/deployment/host-prereq.md
Labels: bug

#575 DOC-3442: Postgres and CockroachDB version number fixing
  content/en/platform/corda/4.8/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.8/enterprise/node/setup/host-prereq.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
  content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
Labels: bug

#576 DOC-3865: Completing instructions on adding class to serialization whitelist
  content/en/platform/corda/4.8/enterprise/serialization.md
Labels: bug

#559 DOC-3867: 4.8.6 CorDapp tutorial bugs
  content/en/tutorials/corda/4.8/os/build-basic-cordapp/basic-cordapp-flows.md
  content/en/tutorials/corda/4.8/os/build-basic-cordapp/basic-cordapp-int-testing.md
  content/en/tutorials/corda/4.8/os/build-basic-cordapp/basic-cordapp-running.md
  content/en/tutorials/corda/4.8/os/build-basic-cordapp/basic-cordapp-state.md
Labels: bug, tutorials

#577 DOC-3215: JDKs for development in platform support matrix
  content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
Labels: bug

#505 DOC-2080 Bug fixes to CENM deployment pages.
  content/en/platform/corda/1.2/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.3/cenm/cenm-cli-tool.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes-auth.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes-farm.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes-idman.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes-nmap.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes-notary.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes-signer.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes-zone.md
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/cenm-cli-tool.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes-auth.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes-gateway.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes-idman.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes-nmap.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes-notary.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes-signer.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes-zone.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/cenm-cli-tool.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes-auth.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes-gateway.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes-idman.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes-nmap.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes-notary.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes-signer.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes-zone.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes-auth.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes-farm.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes-idman.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes-nmap.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes-notary.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes-signer.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes-zone.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes-auth.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes-gateway.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes-idman.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes-nmap.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes-notary.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes-signer.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes-zone.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes-auth.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes-gateway.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes-idman.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes-nmap.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes-notary.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes-signer.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes-zone.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes-auth.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes-gateway.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes-idman.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes-nmap.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes-notary.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes-signer.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes-zone.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes.md
Labels: bug

#578 DOC-155: Add links to docker images to platform support matrix
  content/en/platform/corda/4.4/enterprise/platform-support-matrix.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.5/enterprise/platform-support-matrix.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.6/enterprise/platform-support-matrix.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.7/enterprise/platform-support-matrix.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
Labels: bug

#581 DOC-430: Adding info on how many nodes can run behind one float/bridge set up
  content/en/platform/corda/4.4/enterprise/node/corda-firewall-upgrade.md
  content/en/platform/corda/4.5/enterprise/node/corda-firewall-upgrade.md
  content/en/platform/corda/4.6/enterprise/node/corda-firewall-upgrade.md
  content/en/platform/corda/4.7/enterprise/node/corda-firewall-upgrade.md
  content/en/platform/corda/4.8/enterprise/node/corda-firewall-upgrade.md
Labels: bug, ps-request

#580 DOC-155-1: Fixing bugs from DOC-155 build
  content/en/platform/corda/4.7/enterprise/platform-support-matrix.md
  content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
Labels: bug, ps-request
