Repository corda/corda-docs-portal, pull requests merged in 2022-03, with the labels that each got.

#582 DOC-2134-2: Refactor Kubernetes CENM deployment page in CENM and CE docs
  content/en/platform/corda/1.3/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.4/cenm/deployment-kubernetes.md
  content/en/platform/corda/1.5/cenm/deployment-kubernetes.md
  content/en/platform/corda/4.5/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/deployment-kubernetes.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/deployment-kubernetes.md
Labels: bug, ps-request

#583 DOC-3825: Updated Mission Mars UI tutorial
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-ui.md
Labels: bug

#584 DOC-2193: Adding note on compound serialization to `RPCOps.startFlow`
  content/en/platform/corda/4.5/enterprise/flow-state-machines.md
  content/en/platform/corda/4.5/open-source/flow-state-machines.md
  content/en/platform/corda/4.6/enterprise/flow-start-with-client-id.md
  content/en/platform/corda/4.6/enterprise/flow-state-machines.md
  content/en/platform/corda/4.6/open-source/flow-start-with-client-id.md
  content/en/platform/corda/4.6/open-source/flow-state-machines.md
  content/en/platform/corda/4.7/enterprise/flow-start-with-client-id.md
  content/en/platform/corda/4.7/enterprise/flow-state-machines.md
  content/en/platform/corda/4.7/open-source/flow-start-with-client-id.md
  content/en/platform/corda/4.7/open-source/flow-state-machines.md
  content/en/platform/corda/4.8/enterprise/flow-start-with-client-id.md
  content/en/platform/corda/4.8/enterprise/flow-state-machines.md
  content/en/platform/corda/4.8/open-source/flow-start-with-client-id.md
Labels: bug, ps-request

#585 DOC-3700: More detail on logging page
  content/en/platform/corda/4.8/enterprise/node/operating/node-administration.md
Labels: bug, ps-request

#556 DOC-3817: Key concepts - node
  content/en/platform/corda/4.8/open-source/key-concepts-node.md
Labels: community edition

#586 DOC-3850 Vault and Softlocking key concept
  content/en/platform/corda/4.8/open-source/key-concepts-vault.md
Labels: community edition

#587 DOC-3819 delete document tradeoffs
  content/en/platform/corda/4.8/open-source/key-concepts-tradeoffs.md
Labels: community edition

#592 DOC-3919: Updated template links in the Run a sample CorDapp tutorial
  content/en/platform/corda/4.8/enterprise/cordapps/tutorial-cordapp.md
  content/en/platform/corda/4.8/open-source/tutorial-cordapp.md
Labels: bug, tutorials

#597 DOC-462: Fix filepath in classname for CorDapp database management
  content/en/platform/corda/4.6/enterprise/cordapps/database-management.md
  content/en/platform/corda/4.7/enterprise/cordapps/database-management.md
  content/en/platform/corda/4.8/enterprise/cordapps/database-management.md
  content/en/platform/corda/4.9/enterprise/cordapps/database-management.md
Labels: bug, ps-request

#600 DOC-3925: Corda Enterprise 4.9 link fixes until Developing CorDapps (excluded)
  content/en/platform/corda/4.9/enterprise/_index.md
  content/en/platform/corda/4.9/enterprise/app-upgrade-notes-enterprise.md
  content/en/platform/corda/4.9/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.9/enterprise/minor-version-node-upgrade.md
  content/en/platform/corda/4.9/enterprise/node-upgrade-notes.md
  content/en/platform/corda/4.9/enterprise/release-notes-enterprise.md
Labels: bug

#601 DOC-521: Added additional info about the stateMachineSnapshot method
  content/en/platform/corda/4.3/enterprise/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.3/open-source/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.4/enterprise/node/operating/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.4/open-source/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.5/enterprise/node/operating/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.5/open-source/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.6/enterprise/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.6/open-source/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.7/enterprise/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.7/open-source/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.8/enterprise/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.8/open-source/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.9/community/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.9/enterprise/node-operations-upgrade-cordapps.md
Labels: enhancement, waiting for SME review

#602 DOC-3929: Fix quasar version number for 4.9
  content/en/platform/corda/4.9/codesamples/healthcheck-runtimeInfo.txt
  content/en/platform/corda/4.9/community/cordapp-build-systems.md
  content/en/platform/corda/4.9/enterprise/app-upgrade-notes-enterprise.md
  content/en/platform/corda/4.9/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.9/enterprise/cordapps/cordapp-build-systems.md
Labels: bug, community edition
