Repository corda/corda-docs-portal, pull requests merged in 2022-01, with the labels that each got.

#497 DOC-3764: Fixed formatting in code snippets.
  content/en/platform/corda/5.0-dev-preview-1/tutorials/run-demo-cordapp.md
Labels: bug

#496 DOC-600: broken links
  content/en/platform/corda/4.0/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.1/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.2/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.3/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.4/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.5/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.6/enterprise/app-upgrade-notes.md
  content/en/platform/corda/4.7/enterprise/app-upgrade-notes.md
Labels: bug, documentation

#498 DOC-3760: Corrected shell jar name. Added link.
  content/en/platform/corda/4.4/enterprise/node/operating/shell.md
  content/en/platform/corda/4.4/open-source/shell.md
  content/en/platform/corda/4.5/enterprise/node/operating/shell.md
  content/en/platform/corda/4.5/open-source/shell.md
  content/en/platform/corda/4.6/enterprise/node/operating/shell.md
  content/en/platform/corda/4.6/open-source/shell.md
  content/en/platform/corda/4.7/enterprise/node/operating/shell.md
  content/en/platform/corda/4.7/open-source/shell.md
  content/en/platform/corda/4.8/enterprise/node/operating/shell.md
  content/en/platform/corda/4.8/open-source/shell.md
Labels: bug

#458 DOC-3365 Fix broken links in Corda OS 4.4 pages
  content/en/platform/corda/4.4/open-source/_index.md
  content/en/platform/corda/4.4/open-source/api-contract-constraints.md
  content/en/platform/corda/4.4/open-source/api-core-types.md
  content/en/platform/corda/4.4/open-source/api-flows.md
  content/en/platform/corda/4.4/open-source/api-scanner.md
  content/en/platform/corda/4.4/open-source/api-stability-guarantees.md
  content/en/platform/corda/4.4/open-source/api-vault-query.md
  content/en/platform/corda/4.4/open-source/app-upgrade-notes.md
  content/en/platform/corda/4.4/open-source/building-a-cordapp-index.md
  content/en/platform/corda/4.4/open-source/changelog.md
  content/en/platform/corda/4.4/open-source/checkpoint-tooling.md
  content/en/platform/corda/4.4/open-source/cli-application-shell-extensions.md
  content/en/platform/corda/4.4/open-source/clientrpc.md
  content/en/platform/corda/4.4/open-source/contributing-flow-state-machines.md
  content/en/platform/corda/4.4/open-source/contributing.md
  content/en/platform/corda/4.4/open-source/corda-configuration-file.md
  content/en/platform/corda/4.4/open-source/corda-network/the-corda-network.md
  content/en/platform/corda/4.4/open-source/corda-network/uat.md
  content/en/platform/corda/4.4/open-source/cordapp-advanced-concepts.md
  content/en/platform/corda/4.4/open-source/cordapp-build-systems.md
  content/en/platform/corda/4.4/open-source/cordapp-constraint-migration.md
  content/en/platform/corda/4.4/open-source/cordapp-overview.md
  content/en/platform/corda/4.4/open-source/cordapp-upgradeability.md
  content/en/platform/corda/4.4/open-source/debugging-a-cordapp.md
  content/en/platform/corda/4.4/open-source/demobench.md
  content/en/platform/corda/4.4/open-source/deploying-a-node.md
  content/en/platform/corda/4.4/open-source/financial-model.md
  content/en/platform/corda/4.4/open-source/flow-state-machines.md
  content/en/platform/corda/4.4/open-source/generating-a-node.md
  content/en/platform/corda/4.4/open-source/hello-world-running.md
  content/en/platform/corda/4.4/open-source/hello-world-template.md
  content/en/platform/corda/4.4/open-source/json.md
  content/en/platform/corda/4.4/open-source/key-concepts-ledger.md
  content/en/platform/corda/4.4/open-source/network-bootstrapper.md
  content/en/platform/corda/4.4/open-source/network-builder.md
  content/en/platform/corda/4.4/open-source/network-map.md
  content/en/platform/corda/4.4/open-source/node-administration.md
  content/en/platform/corda/4.4/open-source/node-explorer.md
  content/en/platform/corda/4.4/open-source/node-operations-upgrade-cordapps.md
  content/en/platform/corda/4.4/open-source/node-upgrade-notes.md
  content/en/platform/corda/4.4/open-source/oracles.md
  content/en/platform/corda/4.4/open-source/release-notes.md
  content/en/platform/corda/4.4/open-source/running-a-node.md
  content/en/platform/corda/4.4/open-source/running-a-notary.md
  content/en/platform/corda/4.4/open-source/serialization-enum-evolution.md
  content/en/platform/corda/4.4/open-source/setting-up-a-dynamic-compatibility-zone.md
  content/en/platform/corda/4.4/open-source/shell.md
  content/en/platform/corda/4.4/open-source/testing.md
  content/en/platform/corda/4.4/open-source/troubleshooting.md
  content/en/platform/corda/4.4/open-source/tut-two-party-flow.md
  content/en/platform/corda/4.4/open-source/tutorial-cordapp.md
  content/en/platform/corda/4.4/open-source/tutorial-observer-nodes.md
  content/en/platform/corda/4.4/open-source/tutorial-tear-offs.md
  content/en/platform/corda/4.4/open-source/upgrading-cordapps.md
  content/en/platform/corda/4.4/open-source/versioning-and-upgrades.md
Labels: bug, documentation, don't merge yet

#503 DOC-3767 CENM Jira Setup: Jira User Privileges
  content/en/platform/corda/1.5/cenm/jira-setup.md
Labels: bug, waiting for SME review

#469 DOC-3698: Improvements to Mission Mars flows tutorial
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-flows.md
Labels: documentation, waiting for SME review, tutorials

#509 DOC-3763: Updated yaml file snippet.
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-running.md
Labels: bug

#510 DOC-3770: fixed broken link in mission mars int tests tutorial
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-int-test.md
Labels: bug, documentation, tutorials

#511 DOC-506: Added info about max supported length of certificate serial number.
  content/en/platform/corda/1.2/cenm/config-pki-tool-parameters.md
  content/en/platform/corda/1.2/cenm/identity-manager.md
  content/en/platform/corda/1.3/cenm/config-pki-tool-parameters.md
  content/en/platform/corda/1.3/cenm/identity-manager.md
  content/en/platform/corda/1.4/cenm/config-pki-tool-parameters.md
  content/en/platform/corda/1.4/cenm/identity-manager.md
  content/en/platform/corda/1.5/cenm/config-pki-tool-parameters.md
  content/en/platform/corda/1.5/cenm/identity-manager.md
Labels: bug

#515 DOC-3762: Add link to gradle plugin page from tutorials pages
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-running.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/run-demo-cordapp.md
Labels: documentation, dependencies

#501 DOC-3709-2 update copy on docs landing page
  themes/doks/layouts/index.html
Labels: theme, doc infrastructure & IA

#516 DOC-3718 make tiles smaller
  themes/doks/layouts/index.html
Labels: theme, doc infrastructure & IA

#518 DOC-347: Marked optional parameters as optional.
  content/en/platform/corda/1.3/cenm/config-network-map-parameters.md
  content/en/platform/corda/1.4/cenm/config-network-map-parameters.md
  content/en/platform/corda/1.5/cenm/config-network-map-parameters.md
Labels: bug

#519 ENT-6555 Added missing artemis keystore details to bridge config in firewall docs
  content/en/platform/corda/4.4/enterprise/node/corda-firewall-component.md
  content/en/platform/corda/4.5/enterprise/node/corda-firewall-component.md
  content/en/platform/corda/4.6/enterprise/node/corda-firewall-component.md
  content/en/platform/corda/4.7/enterprise/node/corda-firewall-component.md
  content/en/platform/corda/4.8/enterprise/node/corda-firewall-component.md
Labels: bug, documentation

#517 DOC-3701 add context around openssl config option
  content/en/platform/corda/4.5/enterprise/operations/deployment/corda-configuration-fields.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/corda-configuration-fields.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/corda-configuration-fields.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/corda-configuration-fields.md
Labels: bug

#417 DOC-3619: Added second contracts tutorial.
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-contract-2.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-contract.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-flows.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-running.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-state-2.md
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-state.md
Labels: documentation, don't merge yet, tutorials

#522 DOC-3715 Added description of how to run db migrations (copied CE to OS)
  content/en/platform/corda/4.0/open-source/docker-image.md
  content/en/platform/corda/4.1/open-source/docker-image.md
  content/en/platform/corda/4.3/open-source/docker-image.md
  content/en/platform/corda/4.4/open-source/docker-image.md
  content/en/platform/corda/4.5/open-source/docker-image.md
  content/en/platform/corda/4.6/open-source/docker-image.md
  content/en/platform/corda/4.7/open-source/docker-image.md
  content/en/platform/corda/4.8/open-source/docker-image.md
Labels: bug, documentation

#523 DOC-3757 DemoBench references removed and page updated
  content/en/platform/corda/4.6/enterprise/cordapps/deterministic-jvm.md
  content/en/platform/corda/4.6/enterprise/demobench.md
  content/en/platform/corda/4.6/enterprise/key-concepts-djvm.md
  content/en/platform/corda/4.6/enterprise/node/deploy/running-a-node.md
  content/en/platform/corda/4.6/enterprise/operations/deployment/running-a-node.md
  content/en/platform/corda/4.6/open-source/demobench.md
  content/en/platform/corda/4.6/open-source/key-concepts-djvm.md
  content/en/platform/corda/4.6/open-source/running-a-node.md
  content/en/platform/corda/4.6/open-source/testing.md
  content/en/platform/corda/4.6/open-source/tools-index.md
  content/en/platform/corda/4.7/enterprise/cordapps/deterministic-jvm.md
  content/en/platform/corda/4.7/enterprise/demobench.md
  content/en/platform/corda/4.7/enterprise/key-concepts-djvm.md
  content/en/platform/corda/4.7/enterprise/node/deploy/running-a-node.md
  content/en/platform/corda/4.7/enterprise/operations/deployment/running-a-node.md
  content/en/platform/corda/4.7/open-source/demobench.md
  content/en/platform/corda/4.7/open-source/key-concepts-djvm.md
  content/en/platform/corda/4.7/open-source/running-a-node.md
  content/en/platform/corda/4.7/open-source/testing.md
  content/en/platform/corda/4.7/open-source/tools-index.md
  content/en/platform/corda/4.8/enterprise/cordapps/deterministic-jvm.md
  content/en/platform/corda/4.8/enterprise/demobench.md
  content/en/platform/corda/4.8/enterprise/key-concepts-djvm.md
  content/en/platform/corda/4.8/enterprise/node/deploy/running-a-node.md
  content/en/platform/corda/4.8/enterprise/operations/deployment/running-a-node.md
  content/en/platform/corda/4.8/open-source/demobench.md
  content/en/platform/corda/4.8/open-source/key-concepts-djvm.md
  content/en/platform/corda/4.8/open-source/running-a-node.md
  content/en/platform/corda/4.8/open-source/testing.md
  content/en/platform/corda/4.8/open-source/tools-index.md
Labels: bug, documentation

#524 DOC-3832 remove announcements page
  content/en/announcements/_index.md
  themes/doks/layouts/index.html
Labels: doc infrastructure & IA

#514 DOC-117: Added note about enabling SSL on all services.
  content/en/platform/corda/1.3/cenm/config-ssl.md
  content/en/platform/corda/1.4/cenm/config-ssl.md
  content/en/platform/corda/1.5/cenm/config-ssl.md
Labels: bug

#530 DOC-3803 Added note for flow management console 1.0.3
  content/en/platform/corda/4.7/enterprise/node/node-flow-management-console.md
  content/en/platform/corda/4.8/enterprise/node/node-flow-management-console.md
Labels: release

#529 DOC-3802 Added note for node management console 1.0.3
  content/en/platform/corda/4.7/enterprise/node/management-console/index.md
  content/en/platform/corda/4.8/enterprise/node/management-console/index.md
Labels: release

#525 DOC-33773-2: new fixes
  content/en/platform/corda/4.8/open-source/debugging-a-cordapp.md
Labels: bug, documentation, waiting for SME review

#533 DOC-3836 Updated notes on Business network membership to version 1.1.2.
  content/en/platform/corda/4.7/open-source/business-network-membership.md
  content/en/platform/corda/4.8/open-source/business-network-membership.md
Labels: release

#534 DOC-3804 Updated alerts and releases re: Log4j 2.17.1
  content/en/release-notes/_index.md
Labels: release

#521 DOC-3698-2: Added the GiftVoucherToFriend flow
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-flows.md
Labels: documentation, enhancement, waiting for SME review, tutorials

#531 DOC-150: Fixed broken links.
  content/en/platform/corda/4.4/enterprise/node/operating/node-database-tables.md
  content/en/platform/corda/4.5/enterprise/node/operating/node-database-tables.md
  content/en/platform/corda/4.6/enterprise/node/operating/node-database-tables.md
  content/en/platform/corda/4.7/enterprise/node/operating/node-database-tables.md
Labels: bug

#538 DOC-214 Fixed broken links to key concepts pages
  content/en/platform/corda/4.0/enterprise/changelog.md
  content/en/platform/corda/4.0/open-source/cipher-suites.md
  content/en/platform/corda/4.2/enterprise/changelog.md
  content/en/platform/corda/4.3/enterprise/changelog.md
  content/en/platform/corda/4.4/enterprise/changelog.md
  content/en/platform/corda/4.4/enterprise/oracles.md
  content/en/platform/corda/4.5/enterprise/oracles.md
  content/en/platform/corda/4.6/enterprise/oracles.md
  content/en/platform/corda/4.7/enterprise/oracles.md
  content/en/platform/corda/4.8/enterprise/oracles.md
Labels: bug, documentation

#535 DOC-3864: Added java code to flows tutorial
  content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-flows.md
Labels: documentation, tutorials

#541 DOC-312: Added link to azure docs. Fixed formatting.
  content/en/platform/corda/4.6/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.7/enterprise/node/operating/node-database-admin.md
  content/en/platform/corda/4.8/enterprise/node/operating/node-database-admin.md
Labels: bug

#544 Doc 3807 update network key concepts
  content/en/platform/corda/4.8/open-source/key-concepts-ecosystem.md
Labels: community edition

#536 DOC-3805 checksums, legal info, and alerts and releases updated
  content/en/release-notes/_index.md
Labels: don't merge yet, release

#545 DOC-3837: Bug fixes in 4.8 tutorials
  content/en/platform/corda/4.8/open-source/tutorials-index.md
  content/en/tutorials/corda/4.8/os/build-basic-cordapp/basic-cordapp-state.md
Labels: bug
