Repository corda/corda-docs-portal, pull requests merged in 2023-05, with the labels that each got.

#1339 remove `requestjoin`
  content/en/platform/corda/5.0/application-networks/creating/members/register.md
  content/en/platform/corda/5.0/application-networks/creating/mgm/register.md
  content/en/platform/corda/5.0/application-networks/creating/notaries.md
Labels: waiting for SME review

#1359 Fe-60 enterprise icon
  content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/static-onboarding.md
  themes/doks/layouts/shortcodes/enterprise-icon.html
Labels: don't review yet

#1360 FE-60: enterprise icon
  content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/static-onboarding.md
  themes/doks/layouts/shortcodes/enterprise-generic-icon.html
  themes/doks/layouts/shortcodes/enterprise-h2-icon.html
  themes/doks/layouts/shortcodes/enterprise-h3-icon.html
  themes/doks/layouts/shortcodes/enterprise-icon.html
  themes/doks/static/icons/enterprise-icon.png
Labels: don't review yet

#1329 migrate existing tutorial
  content/en/platform/corda/5.0/developing-applications/basic-cordapp/_index.md
  content/en/platform/corda/5.0/developing-applications/basic-cordapp/basic-cordapp-structure.png
  content/en/platform/corda/5.0/developing-applications/basic-cordapp/contract.md
  content/en/platform/corda/5.0/developing-applications/basic-cordapp/flows.md
  content/en/platform/corda/5.0/developing-applications/basic-cordapp/setup.md
  content/en/platform/corda/5.0/developing-applications/basic-cordapp/state.md
  content/en/platform/corda/5.0/developing-applications/basic-cordapp/testing.md
Labels: tutorials
